### PR TITLE
Add support to query by ID from the file system

### PR DESCRIPTION
**Pull request by aerowisca**
## Related Issue
  - Info about Issue or bug

Closes: #337

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

result

### CODE REVIEW

**Comment by SanskritiHarmukh** [comment]
@Sarthak160 can you please review this PR?

**Comment by SanskritiHarmukh** [comment]
@aerowisca you can read and sign the CLA document. Also, signoff your commits and pass the DCO check by running, 
In your local branch, `git rebase HEAD~3 --signoff` and
Force push your changes to overwrite the branch: `git push --force-with-lease origin main`

**Comment by Sarthak160** [comment]
Sure ✌🏻

**Comment by Sarthak160** [comment]
> @Sarthak160 can you please review this PR?

Sure ✌🏻

**Comment by aerowisca** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aerowisca** [comment]
Thanks @SanskritiHarmukh  I've read and signed the CLA document, and also signed off the commits. 
@Sarthak160  This PR is now ready for review.

**Comment by Sarthak160** [comment]
Hey @aerowisca Can you please add a test for functionality. Currently we are maintaining 75% code coverage . We use keploy itself to record tests for any PR . You can refer this [PR](https://github.com/keploy/keploy/pull/471) for more clarity

**Comment by aerowisca** [comment]
Hi @Sarthak160 , currently it's not possible to add tests via keploy easily for this CR, because it has schema changes that invalidates other mocks, and a new CR would also be required on the go-sdk repo to properly sync the dependencies. Moreover, without the code being merged in go-sdk-repo, it'd be difficult to get in the latest schema changes.

Is it fine if I add unit tests for the feature instead? (We can add keploy tests once changes in both keploy and go-sdk repo are merged).

**Comment by Sarthak160** [comment]
> Hi @Sarthak160 , currently it's not possible to add tests via keploy easily for this CR, because it has schema changes that invalidates other mocks, and a new CR would also be required on the go-sdk repo to properly sync the dependencies. Moreover, without the code being merged in go-sdk-repo, it'd be difficult to get in the latest schema changes.
> 
> Is it fine if I add unit tests for the feature instead? (We can add keploy tests once changes in both keploy and go-sdk repo are merged).

Hmm @aerowisca makes sense , yes  unit-test will be the way for now . @re-Tick has already written some of the unit tests for test export functions .

**Pull request closed without merging**
