### PR TITLE
feat: ignore tests

### PR DESCRIPTION
**Pull request by charankamarapu**
1. Created separate helper functions for flag validation 
    -  viper binding and unmarshalling
    -  validating flags 
    - auto generate config
2. Added ignore test functionality.

Need to discuss on bypass ports and selectedTests in the config and flags

### CODE REVIEW

**Review by Sarthak160 — APPROVED** [review]
LGTM

**Comment by Sarthak160** [comment]
@gouravkrosx Can you look into the failing test bench .

**Comment by gouravkrosx** [comment]
@charankamarapu, As discussed with the team, we should only save the below flags in the config file taken from the command and the rest should be set as default.
The flags that can be saved with the new config file generated are.
1. Command
2. Delay
3. Container Name
4. ApiTimeout
5. Ignore Ordering
6. Language
7. DisableANSI
8. App Name
9. Skip Coverage
10. Mocking

The current test bench will pass once you make these changes, because right now it is failing because it is not able to check the report for `test-set-1`, due to the selected tests config saved in the file.

**Comment by charankamarapu** [comment]
@gouravkrosx what is mocking..?

**Comment by charankamarapu** [comment]
you dont need noise..?

**Comment by gouravkrosx** [comment]
@charankamarapu 
> what is mocking..?

It is a flag used to disable the mocking feature of keploy during test mode. This is useful when someone wants to use keploy tests to check the e2e flow in real environment.

**Comment by charankamarapu** [comment]
@gouravkrosx @Sarthak160 Please have a look.

**Review by Sarthak160 — APPROVED** [review]
LGTM

**Pull request merged**
