### PR TITLE
rename delay flag to --startup-time

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
## Related Issue
  - Info about Issue or bug

Closes: #780 

#### Describe the changes you've made
Renamed delay flag with --startup-time
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by re-Tick** [comment]
Hi @SaumyaBhushan, you have to remove the delay flag also from the cmds. for example: [here](https://github.com/keploy/keploy/blob/e0d6855013ee9fd807c9412ac3e4ea3eed3e3011/cmd/record.go#L104)

**Comment by SaumyaBhushan** [comment]
> Hi @SaumyaBhushan, you have to remove the delay flag also from the cmds. for example: [here](https://github.com/keploy/keploy/blob/e0d6855013ee9fd807c9412ac3e4ea3eed3e3011/cmd/record.go#L104)

Hi @re-Tick ! Thanks for pointing it out . Just for clarification Does it need to renamed as well ?

**Review by nehagup — CHANGES_REQUESTED** [review]
@SaumyaBhushan thanks for the PR! There a change in the flag name basis on the team discussion. We're planning to make it "--startup-delay"

**Comment by SaumyaBhushan** [comment]
Sure @nehagup I will take alook

**Comment by nehagup** [comment]
@SaumyaBhushan are you working on this?

**Review by nehagup — COMMENTED** [review]
Hi @SaumyaBhushan closing this for now, please re-open once you update. :)

**Pull request closed without merging**
