### PR TITLE
[docs]: Update Readme and add docs site reference links

### PR DESCRIPTION
**Pull request by nehagup**
#### Describe the changes you've made
Update Readme and add docs site reference links

Shortened readme basis on user-interviews and added docs website links

## Type of change
Documentation

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@nehagup can you please stash all these commits into a single commit :)

**Comment by nehagup** [comment]
@Sarthak160 @slayerjain any suggestions on why the build pipeline is failing in test stage, since there are no modifications on the test-suite or server codebase. 🤔

**Comment by slayerjain** [comment]
It should be fixed by a fix added in by @Sarthak160  #92

**Review by slayerjain — APPROVED** [review]
The changes look really good! ❤️

**Pull request merged**
