### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by himanshu1221**
## Related Issue
  - Updated Readme

Closes: #415 

#### Describe the changes you've made

- added documentation section
- added contributing guidelines

## Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by himanshu1221** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by himanshu1221** [comment]
recheck

**Comment by himanshu1221** [comment]
> _**I have read the CLA Document and I hereby sign the CLA**_

I have read the CLA Document and I hereby sign the CLA

**Comment by himanshu1221** [comment]
> recheck

recheck

**Comment by himanshu1221** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
recheck

**Pull request merged**
