### PR TITLE
[Refactored]: Removed explicit chmod commands

### PR DESCRIPTION
**Pull request by Yaxhveer**
## Related Issue
  - Info about Issue or bug

Closes: #1534 

#### Describe the changes you've made
Refactored the keploy codebase to remove explicit chmod commands

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Yaxhveer** [comment]
@slayerjain Please review the pull request.

**Comment by PranshuSrivastava** [comment]
Hey @Yaxhveer  the task was to remove the use of chmod, not use it with the os library, please update your approach to not use chmod at all.

**Comment by Yaxhveer** [comment]
@PranshuSrivastava Working on different approach.

**Comment by Yaxhveer** [comment]
@PranshuSrivastava How do you want the task to be done? Since we have to use chmod to change the permission of an existing file or am I missing something?

**Comment by PranshuSrivastava** [comment]
You need to check if there is any other way of doing it apart from using chmod.

**Pull request closed without merging**
