### PR TITLE
change log level to error instead of fatal

### PR DESCRIPTION
**Pull request by aksh-02**
## Related Issue
  (https://github.com/keploy/keploy/issues/150)
Closes: https://github.com/keploy/keploy/issues/150

#### Describe the changes you've made
Changed log level to Error from Fatal so that keploy doesn't exit in case of no internet

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### CODE REVIEW

**Comment by aksh-02** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by slayerjain** [comment]
@aksh-02 thanks for the PR!
I feel this could be a `debug` instead of an error because telemetry doesn't impact how users use keploy.  

Also, please do sign-off your commit to pass the DCO check.

**Comment by slayerjain** [comment]
@re-Tick @Sarthak160  any idea why the tests keep failing on this PR?

**Comment by slayerjain** [comment]
thanks, @aksh-02 . We've fixed the issue with the tests. merging this.

**Review by slayerjain — APPROVED** [review]
LGTM

**Pull request merged**
