### PR TITLE
chore: rename the container in docker-compose

### PR DESCRIPTION
**Pull request by EdwinWalela**
## Related Issue

Closes: [#102 ](https://github.com/keploy/keploy/issues/102)

#### Describe the changes you've made
Renamed  the `web_1` container to `keploy` 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by nehagup** [comment]
Hey @EdwinWalela could you please try running this locally and testing it first? :)

**Comment by EdwinWalela** [comment]
@nehagup  My bad, I did test it locally but renaming the service slipped my mind

**Comment by slayerjain** [comment]
@EdwinWalela can you please remove the `container_name` field? it doesn't look like its required here

**Comment by EdwinWalela** [comment]
@slayerjain You are right, it is repetitive. I have omitted it

**Review by slayerjain — APPROVED** [review]
LGTM. Thanks, @EdwinWalela!

**Comment by nehagup** [comment]
@EdwinWalela Congratulations! Please feel free to add yourselves here https://github.com/keploy/keploy#-our-valuable-contributors- 😄

**Pull request merged**
