### PR TITLE
Added new version available message to keploy whenever there is update

### PR DESCRIPTION
**Pull request by jaiakash**
## Related Issue
  - This PR added a feature that displays a new version available message (if any) whenever their keploy is run.

Closes: #2047 
Closes: #2071 

#### Describe the changes you've made
Add function in `main.go` that check `currentVersion` with `latestVersion` from github API and displays message accodingly.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| No SS | 
Screenshot 2024-07-19 at 1 36 51 PM
 |

### CODE REVIEW

**Comment by jaiakash** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jaiakash** [comment]
Hi @Sonichigo @Swpn0neel I have used https://github.com/keploy/keploy/blob/55df9dc18bb1f1208ab7e57d5b7afea0900709a5/utils/utils.go#L313 function to check for the latest version and added the newly created [`checkForUpdate`](https://github.com/jaiakash/keploy/blob/676c9820f749d69b8041c3c6bf95d0db8bc91f93/main.go#L59) in `main.go` to check for new update on every run of Kelpoy.

There are some queries from my side.
1. For now the text is printed as plain text. If we want the design as outline in issue #2047 , we have to use external go library like [term](https://github.com/buger/goterm).  Shall I use that or is there a better way?
2. This new `checkForUpdate` is run everytime keploy is run. But shouldn't we hide that message when user directly run `keploy update` to hide repetitive message? Lmk what you think.

**Review by Sarthak160 — COMMENTED** [review]
@jaiakash Please move this method to utils itself. Its better to implement less function definations in main.

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
If the user is using the latest version, we shouldn't print it (to avoid repetition)

**Comment by jaiakash** [comment]
> If the user is using the latest version, we shouldn't print it (to avoid repetition)

Is user is using the latest version it wont be printed.

**Review by Swpn0neel — COMMENTED** [review]
@Sarthak160 Currently they are printing the statement in plain text without any decorations, so should we keep that? Otherwise, they can use an external dependency to decorate it...

**Comment by jaiakash** [comment]
Hi @Sarthak160 @Swpn0neel any update on the formating of the text? As of now this is now its printed

Screenshot 2024-07-19 at 1 36 51 PM

We can use libraries like [term](https://github.com/buger/goterm) to decorate it. Let me know whats the final decision.

**Comment by Sarthak160** [comment]
@jaiakash We can simply add a progress bar which will pop if user accepts to download the newer version.

**Comment by jaiakash** [comment]
> @jaiakash We can simply add a progress bar which will pop if user accepts to download the newer version.

@Sarthak160 Do you mean the progress bar when a user downloads the update? This PR only add the message that shows the availability of update whenever keploy is run. User have to manually type `keploy update` to update keploy. 

That progress bar makes more sense if we add the progress bar in that command. Let me know what you think and hence I can update the PR accodingly.

**Comment by Swpn0neel** [comment]
So, if the user is on an outdated version, we'll show them that (which are already doing right now). Then, we'll prompt the user if they want to update the latest version or not... If yes, then we'll update it and it should've a progress bar for that!

**Comment by jaiakash** [comment]
Understood, so i have to add progress bar for update operation (it can be when user press `y` during prompt of new update or user directly runs `keploy update` command). 

What I am doing right now, I would edit the logic at https://github.com/keploy/keploy/blob/e0139bb35646549441670355c51f36615cece39e/cli/update.go#L19

to show progress bar. 

Can I use this library - https://github.com/schollz/progressbar for progress bar.
@Swpn0neel please feel free to give your suggestions.

**Comment by Swpn0neel** [comment]
Could you please check if we're already using a library for progress bar or not? If not, then we can surely proceed with the one you suggested!

**Comment by Sonichigo** [comment]
@jaiakash any update?

**Comment by jaiakash** [comment]
Hello I need a bit of help. 
My approach for now is, in case user press `y` during prompt, it should execute same code of `keploy update`, this https://github.com/jaiakash/keploy/blob/7a71cbe1bb3eff31799448b90298401fd1386993/pkg/service/tools/tools.go#L44 
 function. And I will add the progress bar logic there so we don't have to rewrite update logic.
 
Right not the problem I am facing is that if I import that function in https://github.com/jaiakash/keploy/blob/7a71cbe1bb3eff31799448b90298401fd1386993/utils/ctx.go#L38 

go is giving me `import cycle not allowed` error. How can I run the cli command `keploy update` directly form my https://github.com/jaiakash/keploy/blob/7a71cbe1bb3eff31799448b90298401fd1386993/utils/ctx.go#L38 function.

**Comment by Sarthak160** [comment]
@jaiakash Ideally it should not prompt when the user is created its own -dev version. Also If we are not updating the keploy version automatically or any action after taking the user input y or n, Then what is the need to take the user's opininion.

**Pull request closed without merging**
