### PR TITLE
added feature self-update keploy docker image

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
## Related Issue
  - The goal is to check for the latest keploy docker image and download that during setup.

Closes: #782 

#### Describe the changes you've made
I updated the README.md file here https://github.com/keploy/keploy#-docker-installation- where we are setting alias .
I think it should be
alias keploy='sudo docker run --pull always --name keploy-v2 -p 16789:16789 --network keploy-network --privileged --pid=host -it -v "$(pwd)":/files -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/bpf:/sys/fs/bpf -v /var/run/docker.sock:/var/run/docker.sock --rm ghcr.io/keploy/keploy' 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
recheck

**Comment by SaumyaBhushan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SaumyaBhushan** [comment]
recheck

**Review by nehagup — APPROVED** [review]
Great! @SaumyaBhushan Thanks.

**Pull request merged**
