### PR TITLE
 added unit tests for octokit module 

### PR DESCRIPTION
**Pull request by Sekhar-Kumar-Dash**
Related Issue
  - Info about Issue or bug

Closes: #354 

#### Describe the changes you've made
Write a unit test for integrations/octokit module's wrappedNodeFetch function
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

test cases are added.
unit test for octokit module using jest

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Sekhar-Kumar-Dash** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/keploy/keploy/tree/main/.github/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by Sekhar-Kumar-Dash** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by developer-diganta** [comment]
@re-Tick  Can you please review this? @Sekhar-Kumar-Dash  Please wait while the maintainers review this. After that you can add this in the completed task list in the gsoc repo!

**Comment by Sekhar-Kumar-Dash** [comment]
> @re-Tick Can you please review this? @Sekhar-Kumar-Dash Please wait while the maintainers review this. After that you can add this in the completed task list in the gsoc repo!

okay thank you

**Comment by re-Tick** [comment]
Hi @Sekhar-Kumar-Dash, these changes should be in Typescript-SDK.

**Comment by Sekhar-Kumar-Dash** [comment]
> 

@re-Tick  can you please review it again i have replaced the older files with new one

**Pull request closed without merging**
