### PR TITLE
[fix]: permissions for keploy folder

### PR DESCRIPTION
**Pull request by AhmedLotfy02**
## Related Issue
  - Unable to delete keploy generated folder due to permission

Closes: #1696

#### Describe the changes you've made
- Adding permissions to the folder

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by EraKin575** [comment]
@AhmedLotfy02 the CI is failing. please check

**Review by AhmedLotfy02 — COMMENTED** [review]
I added path validation and sanitization.

**Comment by AhmedLotfy02** [comment]
I checked os.Chmod instead of os.exec but it gives permissions to the directory but not for the inside folders
image

**Comment by shivamsouravjha** [comment]
tried this locally, doesn't work, not only does the Keploy folder  isn't deleted, even normal keploy doesn't work 
image

**Comment by shivamsouravjha** [comment]
image
solve this as well

**Comment by shivamsouravjha** [comment]
@AhmedLotfy02 please update the PR as pipeline is failing, also fix the conflicts.

**Comment by shivamsouravjha** [comment]
closing the PR as issue is solved

**Pull request closed without merging**
