### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by cassiozareck**
## Related Issue
There is no open issue directly related to this PR. However, this PR has to do with the improvement of seperation of concerns in the Keploy's codebase. This enhancement aims to boost its scalability and reliability by increasing testable areas and a more granular approach that follows SOLID principle (especially the Dependency Injection).

#### Describe the changes you've made
I've refactored the fs/mock file to instead of have the concern of IO operation as well yaml serializing and conversion to types like model.TestCase[] it delegates the first two concerns onto another module I've create called YamlHandler. This module has the concern of read, write and serialize yamls, while the mockExport uses it to get those yaml as well write go objects (such as model.Mock) without have to worry about serializing the data or do raw IO operations.

More importantly, I've implemented the Dependency Injection principle within mockExport, allowing us to stub the YamlHandler and write tests for it. This isolates the component from real IO operations, giving us greater control and avoiding unnecessary interactions with the file system, which could mess the real file system as well modify files that weren't suppose to be modified. As mockExport can now be isolated I've added new tests on it that have improved Keploy's code coverage, as demonstrated in the screenshot below. 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added
Yes and it improves the Keploy's test coverage

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
No unusual behaviour

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)
Screenshot from 2023-04-28 17-17-15

### CODE REVIEW

**Comment by re-Tick** [comment]
Build is failing because the "yamlHandler" argument is not passed "NewMockExportFS" function. Also there should be a constructor function for the `YamlHandlerImpl` struct.

**Comment by cassiozareck** [comment]
@re-Tick Sorry for that I ran the tests and forgot to see if the project was building correctly! Fixed

**Comment by re-Tick** [comment]
Hi @cassiozareck, I have tried the changes with a sample app. The mocks for the test-case are not recorded properly. A "mocksmock-1.yaml" is created instead of the "mocks/mock-1.yaml". This maybe due to the missing path joining in the WriteAll of fs/mocks.go

**Comment by cassiozareck** [comment]
Solved! After a few time a discovered another issue that path sometimes was being concatenated but I solved too. Now the build is working

**Comment by Sonichigo** [comment]
@cassiozareck Can you please sign the DCO? @re-Tick can you please review the updated changes ?

**Comment by Sarthak160** [comment]
This PR is stale since we migrated to V2 which has newer code structure .

**Pull request closed without merging**
