### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Krishnakalani111**
## Related Issue
  - alt attribute was not present for the img tag in README.md

Closes: #967 

#### Describe the changes you've made
I have successfully added alt attribute with proper naming in the README.md

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by nehagup — APPROVED** [review]
@Krishnakalani111 the issue linked to this PR is for the docs repo which is for keploy.io/docs website. 

The images alt needs to be changed there. 
However, merging these changes since it makes sense.

**Comment by nehagup** [comment]
@Krishnakalani111 please sign the CLA and DCO.

**Comment by Krishnakalani111** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Krishnakalani111** [comment]
@nehagup i have signed the CLA , could you update the status of my PR

**Review by nehagup — APPROVED** [review]

**Pull request merged**
