### PR TITLE
[Feature]: Make generating TestReports files optional

### PR DESCRIPTION
**Pull request by Akash-Singh04**
## Related Issue
  - Feature Update

Closes: #1393 

#### Describe the changes you've made
Added a Flag ```--generateTestReports``` to ```keploy test``` and ```config file``` that will allow the user to choose if they want to generate the Test Reports or not, which is set to true by default. If the flag is set to false via ```generateTestReport=false``` in CLI or config, the Test Report will not be generated

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added
NIL
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NIL
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Akash-Singh04** [comment]
@gouravkrosx Awaiting review on this

**Comment by gouravkrosx** [comment]
@Akash-Singh04 
In the serve command, we are [reading](https://github.com/keploy/keploy/blob/main/pkg/graph/schema.resolvers.go#L114) the testReport file to get the status of the test run. You have not considered that case.

**Comment by Akash-Singh04** [comment]
@gouravkrosx What should be the intended behaviour here? Should be pass in the flag to the place we are reading the TestReport file in serve command and add handling to not read it? There is already error handling present for when the TestReport is not present.

**Comment by gouravkrosx** [comment]
You should make the file in the serve command and then delete it after the command execution is completed.

**Pull request closed without merging**
