### PR TITLE
Add docker internal client to extract network from container

### PR DESCRIPTION
**Pull request by aerowisca**
## Related Issue
  - Info about Issue or bug

Closes: #600 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Sarthak160** [comment]
@aerowisca , This PR only comprises of client interface and it's implementation. Since earlier there were frequent changes to the docker codebase in keploy , But now there is no such case and you can connect your client instance with `proxy/utils` .

**Comment by aerowisca** [comment]
Thanks @Sarthak160  for the info. Will start work on integrating the client with actual application.

**Comment by Sarthak160** [comment]
Hey @aerowisca Can you look at this first , as it has now become urgent to launch V2 for docker users .

**Comment by aerowisca** [comment]
@Sarthak160  Updated the PR with the integration of the docker client in hooks package. I tested it out with a simple docker container, Keploy was able to join the network of the application's docker container.

The docker-compose seems to be broken (due to unrelated changes). I'm initiating a discussion on the slack channel regarding the same.

**Comment by aerowisca** [comment]
This PR is tested and ready to be merged for standalone docker containers. For making it work with docker-compose, there will be possible design changes in other sections of the code, which we can track in a different issue.

[Slack thread for reference](https://keploy.slack.com/archives/C03NWV6D02G/p1692429449023149)

**Comment by aerowisca** [comment]
Update: The PR has been tested for `docker run` as well as `docker compose`.

**Review by gouravkrosx — APPROVED** [review]
LGTM

**Pull request merged**
