### PR TITLE
[feature]: add test pipeline for testing Postgres parser using different applications

### PR DESCRIPTION
**Pull request by harshsbhat**
closes [[feature]: add test pipeline for testing Postgres parser using different applications ](https://github.com/keploy/keploy/issues/1868)
This pull request adds a new GitHub Actions workflow file named test-go-postgres.yml for testing the GinApp application with PostgreSQL. The workflow is designed to automate the testing process and includes the following steps:

**Checkout Repository:** 
Checks out the main repository where the workflow is defined.
Download Keploy Build Binary: Downloads a Keploy build binary artifact from the actions artifact storage.
Give Permission to Binary: Sets executable permissions for the Keploy build binary.
Download Latest Keploy Binary: Downloads the latest Keploy binary release from GitHub and moves it to /usr/local/bin.
Get the Pilot for Tests and Mocks Assertion: Downloads the latest pilot binary for test and mock assertions, sets the executable permission, and moves it to /usr/local/bin.
Checkout to the Samples-Go Repository: Checks out the samples-go repository at the native-linux branch.
Build the Gin-Postgres Application: Navigates to the gin-postgres directory and builds the Go application.
Add Noisy Fields in the Config File: Placeholder step for adding any noisy fields in the configuration file if required.
Run Testing Script for Gin-Postgres Application: Uses a custom GitHub action (.github/actions/tester) to run the testing script for the gin-postgres application with specified parameters.

**PostgreSQL Service:**
Services Section: Configures a PostgreSQL service using the postgres:latest Docker image.
Environment Variables: Sets up the POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB environment variables.
Ports and Health Checks: Exposes port 5432 and sets up health checks to ensure the PostgreSQL service is ready before running the tests.
This new workflow ensures that the GinApp application using PostgreSQL is properly tested with Keploy, automating the setup and execution of tests in a CI/CD pipeline.

**Changes Introduced:**
Added a new GitHub Actions workflow file: .github/workflows/test-go-postgres.yml.
Instructions for Reviewers:
Please review the new workflow file for accuracy and completeness.
Ensure that the PostgreSQL service configuration aligns with the application's requirements.
Verify that the steps and commands for building and testing the application are correct.

I have read the CLA Document and I hereby sign the CLA.

### CODE REVIEW

**Comment by harshsbhat** [comment]
PR for issue #1880  @gouravkrosx

**Comment by harshsbhat** [comment]
recheck

**Comment by harshsbhat** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/keploy/keploy/tree/main/.github/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by harshsbhat** [comment]
I have read the CLA Document and I hereby sign the CLA .

**Comment by harshsbhat** [comment]
recheck

**Comment by slayerjain** [comment]
recheck

**Comment by harshsbhat** [comment]
recheck

**Comment by harshbhat04** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by harshbhat04** [comment]
recheck

**Comment by gouravkrosx** [comment]
@harshbhat04, The workflow has not been triggered, Please check.

**Comment by shivamsouravjha** [comment]
closing the PR as its inactive and a lot of conflicts, feel free to open when these issues are fixed

**Pull request closed without merging**
