### PR TITLE
fix:keploy CLI logs error message when command is unknown

### PR DESCRIPTION
**Pull request by khareyash05**
## Related Issue
  - Info about Issue or bug

Closes: #1853 

#### Describe the changes you've made
Added functionality for logging out when command is unknown

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by khareyash05** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by khareyash05** [comment]
This will work for now. But a better way can be to check the command before it is executed. Trying to work on it!

**Comment by charankamarapu** [comment]
I think there will be a inbuilt feature in cobra to do this, please the tool once.

**Comment by khareyash05** [comment]
> I think there will be a inbuilt feature in cobra to do this, please the tool once.

on it!

**Comment by khareyash05** [comment]
> I think there will be a inbuilt feature in cobra to do this, please the tool once.

Hey @charankamarapu I couldnt find the inbuilt functionality, if you could help with that. Thanks

**Comment by charankamarapu** [comment]
error is already inbuilt it is just that it is not printed print the error after rootCmd.Execute(). But please look what all other errors are printed I mean we are already logging errors , printing errors again will not be proper.

**Review by charankamarapu — APPROVED** [review]
LGTM

**Pull request merged**
