### PR TITLE
Add support to query by ID from the file system

### PR DESCRIPTION
**Pull request by aerowisca**
## Related Issue
  - Info about Issue or bug

Closes: #337 

#### Describe the changes you've made
Adds support to get test case from filesystem by ID

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

result

### CODE REVIEW

**Comment by aerowisca** [comment]
Hi @Sarthak160  I've added the unit tests as discussed. Had to close the close the previous PR and open a new one as I didn't have a dedicated branch for that feature, leading to lots of merge conflicts.

**Comment by aerowisca** [comment]
CC: @SanskritiHarmukh

**Review by Sarthak160 — APPROVED** [review]
I have tested and reviewed code changes in my local , It looks good to me .

**Comment by aerowisca** [comment]
Thanks @Sarthak160  Could you then add the required labels for GSOC?

**Comment by Sarthak160** [comment]
This PR is stale since we migrated to V2 which has newer code structure .

**Pull request closed without merging**
