### PR TITLE
added workflows to test http app

### PR DESCRIPTION
**Pull request by jaydee029**
## Related Issue
  - For issue #1871 

#### Describe the changes you've made
This PR adds workflows to test http app, Another supporting PR adds the required http app to samples-go [here](https://github.com/keploy/samples-go/pull/113)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

image

### CODE REVIEW

**Comment by jaydee029** [comment]
Hey, since the http app is not yet merged in the samples-go repo, the workflows can't access that. Also I ran these workflows locally to, the logs are [here](https://github.com/jaydee029/http-pokeapi/actions/runs/10211556334). They ran infinitely, what can be improved ?

**Comment by gouravkrosx** [comment]
@jaydee029 Please first review and get your HTTPS application merged, since we need HTTP mocks as well. Then only it will contribute to coder coverage and cover HTTP parser code path. And, you need to make 2 pipelines for the same application, you can refer to the existing pipeline of gin-mongo.

**Comment by jaydee029** [comment]
About the http app, I commented on the PR itself that you just closed,  About the workflows, I used a matrix to include 2 workflows in one, which run separately. Thanks.

**Comment by gouravkrosx** [comment]
Your sample app PR has been merged, can you please correct this PR also? Please follow: https://keploy.io/docs/keploy-explained/testing-guide/#testing-phase-

**Comment by gouravkrosx** [comment]
@jaydee029 Your sample app PR has been merged, can you please correct this PR also? Please follow: https://keploy.io/docs/keploy-explained/testing-guide/#testing-phase-

**Comment by PranshuSrivastava** [comment]
Closing as this is stale

**Pull request closed without merging**
