### PR TITLE
added instructions after dependency wrapping

### PR DESCRIPTION
**Pull request by Anshika-sona**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!  
added the instructions after dependency wrapping .

## Type of change Documentation 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Anshika-sona** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Anshika-sona** [comment]
$ git commit -s -m 'This is my commit message

**Comment by Anshika-sona** [comment]
$ git commit -s -m 'This is my commit message

**Review by nehagup — COMMENTED** [review]
Thanks for opening the PR @Anshika-sona 

Can you please either create an issue for this PR or write a detailed description of what was the requirement/need?

Also, please sign the DCO by following the instructions given in the details of failing DCO check.

**Comment by slayerjain** [comment]
@Anshika-sona I read your comments in the file.

I agree that while trying to wrap a class which doesn't implement an interface, the wrapper may require code changes wherever the original is being used. That's currently a limitation of how the wrapping works, if you want to instrument your class. 

To test the wrapper, you can obviously create a simple original object, wrap it, and see it returns the original object back. Since it's a very thin wrapper, it needs to be tested only once (by the author who is writing the wrapper).

**Pull request closed without merging**
