### PR TITLE
feat: added example of filtering urls and headers

### PR DESCRIPTION
**Pull request by narharim**
## Related Issue
  - Info about Issue or bug

- Closes: #1389

#### Describe the changes you've made
added filtering example for url methods and request header and change config file permissions

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by narharim** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by narharim** [comment]
@Sarthak160 have a look at it

**Comment by charankamarapu** [comment]
@narharim @Sarthak160 Please check if this issue still persists after refactor changes that are merged in main and continue with the issue. There is not much changes with respective to this on refactor.

**Comment by re-Tick** [comment]
Please resolve conflicts.

**Comment by re-Tick** [comment]
Closing this PR due to inactivity. The current status is that there are merge conflicts. Please fix it and re-open

**Pull request closed without merging**
