### PR TITLE
fix: updated version of keploy in docker container

### PR DESCRIPTION
**Pull request by officialasishkumar**
## Related Issue
updated version of keploy to v2.0.0 in docker container 

Closes: (keploy/keploy#781)

#### Describe the changes you've made
I have changed the version of keploy to v2.0.0 using ldflags in Dockerfile.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code
 N/A
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

image

### CODE REVIEW

**Comment by officialasishkumar** [comment]
done @charankamarapu

**Comment by Sarthak160** [comment]
@officialasishkumar  Can you please Sign the Above CLA ?

**Comment by officialasishkumar** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by officialasishkumar** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by officialasishkumar** [comment]
recheck

**Comment by officialasishkumar** [comment]
Hi @charankamarapu , can you please review this PR?

**Comment by charankamarapu** [comment]
sure will do it by EOD.

**Comment by charankamarapu** [comment]
Hi @officialasishkumar , Majorly we have two type of versions 
1. one is for developers where "-dev" is added to the version indicating that a developer has cloned the repo and running keploy as a developer .
2. other one is for user where you can only see version without "-dev" indicating a user is running Keploy by getting the keploy image from this link - ghcr.io/keploy/keploy . When ever a release is made a docker image will be pushed here and users use it .

Please make changes in such a way that when users run it , it should show the just version and when developers run it, it should show verison+"-dev" . You achieve this for users by finding the Github action which pushes the docker image to ghcr.io/keploy/keploy and inject version in it . For developers we prefer nothing should be hardcoded . Please find a way to inject the version which developer pulled .

**Pull request closed without merging**
