### PR TITLE
update:  ebpf object files

### PR DESCRIPTION
**Pull request by charankamarapu**
Recent changes to ebpf required more kernel version. Fixed it so that the minimum kernel required will stay at 5.15

### CODE REVIEW

**Comment by gouravkrosx** [comment]
@charankamarapu 
How about if we add verifier logs as well when the logger level is `debug` or just `info`?

**Comment by charankamarapu** [comment]
cool let me add them

**Comment by charankamarapu** [comment]
added the debug log

**Review by gouravkrosx — APPROVED** [review]
LGTM!

**Pull request merged**
