### PR TITLE
Adding details of the only unit test case file needed.

### PR DESCRIPTION
**Pull request by Hermione2408**
## Related Issue
  - Adding details of the only unit test case file needed

Closes: #60

#### Describe the changes you've made
Added the details in the README.md file. Currently, only the code of the file is mentioned. Added details for more clarity such as filename and file location.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

`NA`

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| originaldoc              | updateddoc |

### CODE REVIEW

**Comment by Hermione2408** [comment]
recheck

**Review by nehagup — CHANGES_REQUESTED** [review]
@Hermione2408 can you only push the changes related to this issue? I see there are other linting/prettifying changes that has been added.

**Comment by Hermione2408** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hermione2408** [comment]
recheck

**Comment by Hermione2408** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by Hermione2408** [comment]
recheck

**Review by nehagup — APPROVED** [review]

**Pull request merged**
