### PR TITLE
Improving test coverage with keploy

### PR DESCRIPTION
**Pull request by cassiozareck**
## Related Issue

  - https://github.com/keploy/keploy/issues/333
#### Describe the changes you've made
Ive improved the test-coverage by more than 0.8% of Keploy using Keploy. To accomplish this I mainly used echo-sql as an iterator to Keploy Client at 6789. The Client was of course intercepted by an Keploy server hosted 6790 used to generate those tests

## Please let us know if any test cases are added
Two tests-cases were responsible for about 0.2% of the tests-cases (73, 74), they were made using echo-sql in record mode. The others are responsible for the 0.6% and were made using interaction between Keploy Client and echo-sql but the same in Test Mode.

- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)
Improvements in test coverage:
Screenshot from 2023-03-13 13-28-24
Keploy actual test coverage:
Screenshot from 2023-03-13 13-28-58

Signed-off-by: Cássio Milczareck <cassiomilczareck@gmail.com>

### CODE REVIEW

**Comment by cassiozareck** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SanskritiHarmukh** [comment]
@nehagup , can  you please review this PR.

**Comment by re-Tick** [comment]
Hi @cassiozareck, currently [this](https://coveralls.io/jobs/116683645/source_files/4453835510#L260) if check block is not called. This can be covered by:
1. Run the keploy binary on 6789(keploy-client, on record mode) and 6790(server, on off mode) on different terminals.
2. Start a sample app on record mode and make API calls to record tcs in sample app.
3. Now, restart the keploy-client(running on 6789) binary
4. Again try to record tcs for sample app

This would run the if check block because keploy will cache the lastIndex of test yaml by reading for test directory of sample app.

**Comment by cassiozareck** [comment]
Hi @re-Tick!
I think the new tests already cover it as I made what you said and the percentage stayed the same. Also, I ran keploy in debug mode to be sure and as I saw yeah it was in fact passing inside lastIndex if/else (value was 18) of the Insert() function.
I cannot be 100% sure this piece of code is being tested on the goveralls because I cannot see the source being executed on it. Ill let a link here if you wanna see it better: https://coveralls.io/jobs/116727931

**Comment by re-Tick** [comment]
Oh okay got it why the line was not running is because Keploy runs recorded test with test_export off due to which this block will not run in CI. Thats why unit tests are written for testCase service.

**Comment by re-Tick** [comment]
Hi @cassiozareck, the changes looks good. Please add the PR link in the GSOC/2023 for respective tasklist.

**Comment by SanskritiHarmukh** [comment]
@cassiozareck can you please pass the DCO check by executing the commands in your local branch? Look into the details at the side to see appropriate commands.

**Comment by SanskritiHarmukh** [comment]
@cassiozareck can you add the PR link corresponding to the issue making a column on your username under CLI Refactoring project?

**Review by re-Tick — APPROVED** [review]

**Comment by cassiozareck** [comment]
Sure

**Comment by re-Tick** [comment]
Hi @cassiozareck, noticed that there are some statements which we can cover in the service/mock file by adding some test in the mock_test.go file. Can you please have a look

**Comment by cassiozareck** [comment]
Sure i'll work on it

**Comment by cassiozareck** [comment]
Hi @re-Tick I improved the test-coverage by testing replaceHttpFields function almost entirely. Im still working on this file to improve the test coverage but I could increase it in **15.7%** already. I've found a way to increase even more soon I'll launch new commits but I've updated the PR so you can already review it.

**Comment by cassiozareck** [comment]
Coverage increased by **7.6%**. Which means a total of **23.3%** increased since before.
old:
Screenshot from 2023-04-08 21-31-13
new:
Screenshot from 2023-04-08 21-26-58

**Comment by Sarthak160** [comment]
This PR is stale since we migrated to V2 which has newer code structure .

**Pull request closed without merging**
