### PR TITLE
add link to demo video

### LINKED ISSUE #53: [feature]: Add Video Demo Url to Readme
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add Keploy Demo Video Url from youtube to Readme.

### Why should this be worked on?

It'll help users to understand via video.

### PR DESCRIPTION
**Pull request by skant7**
fixes #53

### CODE REVIEW

**Comment by nehagup** [comment]
Thanks for creating the PR @skant7 👍
Could you please change the width of the image to 50%. Currently the image added is not aligning with the textSize in the other sections.   

Please feel free to reach out if you have any questions. 🙂

**Review by nehagup — CHANGES_REQUESTED** [review]
Image is currently occupying full area. Needs to be aligned with other Text sizes in the Readme. Maybe we can reduce the width to 50%. 

You can also use an html element 
`<a href="link">link-to-video-demo</a>
`

**Review by nehagup — APPROVED** [review]
LGTM

**Comment by slayerjain** [comment]
It's showing lower code coverage because the ci pipeline didn't have access to the GitHub secrets. This is now fixed with #55

**Pull request merged**
