### PR TITLE
Fix README Test Example

### PR DESCRIPTION
**Pull request by CypherpunkSamurai**
Fixed Test Example under 'Integration with native Go test framework' section of README.md

## Related Issue
  - #135

Closes: #135

#### Describe the changes you've made
- The file name was mentioned before the code sample block for easier understanding. 
- Code sample runtime error was fixed that was causing it to not compile.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Please let us know if any test cases are added

NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **image** | <b>image</b> |

### CODE REVIEW

**Comment by CypherpunkSamurai** [comment]
I have read the CLA Document and I hereby sign the CLA

- @CypherpunkSamurai

**Comment by CypherpunkSamurai** [comment]
recheck

**Comment by CypherpunkSamurai** [comment]
Also if possible, I'd really appreciate if you please add hacktoberfest accpeted tag :D

**Review by nehagup — APPROVED** [review]
LGTM! Thanks! 👏

**Pull request merged**
