### PR TITLE
updating variable and corresponding function name 

### PR DESCRIPTION
**Pull request by shivamsouravjha**
## Related Issue
  -Updating function names and variables for IP address of user.

#### Describe the changes you've made
Updating name for function and variables for IP address in struct and corresponding function 
 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
recheck

**Review by gouravkrosx — APPROVED** [review]
LGTM

**Comment by shivamsouravjha** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shivamsouravjha** [comment]
recheck

**Pull request merged**
