### PR TITLE
feat: add a custom matching logic for postgres parser

### PR DESCRIPTION
**Pull request by Sarthak160**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
1) Write a custom and stateful matching logic for postgres parser .
2) Mocks are now editable, one can change the the row values and see changed response acc to that.

So, code refactoring acc to refactor branch has to be done, can test and check functionality for now .
only 1% test might fail, because there is a bug in the petclinic app or the way the ORM is operating queries. As I observed very few times a random query especially for select pets is happening, which was not even occured for that particular testcase during record is occuring in test mode. I have handled it by returning the null rows or No Data row packet, otherwise it would have given mismatch by matching for that query by some other test's mock.
So here we can add a check in petclinic if the pet values are null don't set the response fields.

Screenshot 2024-03-03 at 2 17 09 AM
Screenshot 2024-03-03 at 2 17 14 AM

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Sarthak160** [comment]
So, code refactoring acc to refactor branch has to be done, can test and check functionality for now .

**Comment by gouravkrosx** [comment]
@Sarthak160 Please update your branch according to the refactored changes.

**Comment by Sarthak160** [comment]
> @Sarthak160 Please update your branch according to the refactored changes.

On it will update soon .

**Comment by Sarthak160** [comment]
Closing due to conflicts with newer main v2, changes are moved to #1711

**Pull request closed without merging**
