### PR TITLE
fix (testCaseDb) : fixes uri filter for reading testcases from mongo collection and sets the modified anchors instead of unset in mongo update.

### PR DESCRIPTION
**Pull request by re-Tick**

### CODE REVIEW

**Comment by slayerjain** [comment]
@re-Tick the commit title is too long. please try to keep the titles short and you can utilize the message body to add more details

**Comment by slayerjain** [comment]
@re-Tick also, we should add an option to disable dedup algo (and keep it disabled by default, until we create a separate mode for it)

**Review by slayerjain — CHANGES_REQUESTED** [review]
added review in previous comments

**Comment by re-Tick** [comment]
Added a boolean to enable deduplication logic for keploy server.

**Review by slayerjain — APPROVED** [review]

**Pull request merged**
