### PR TITLE
Fixed a typo in the documentation

### PR DESCRIPTION
**Pull request by michaelgrigoryan25**

### CODE REVIEW

**Review by slayerjain — APPROVED** [review]
Thanks for the correction @michaelgrigoryan25 ! ❤️

Since we conventional commits, editing your commit message and merging 👍

**Comment by slayerjain** [comment]
also please feel free to join our slack channel and become part of our community :)

**Comment by michaelgrigoryan25** [comment]
> also please feel free to join our slack channel and become part of our community :) 

Sure! Do you have a Discord channel as well by any chance?

**Comment by slayerjain** [comment]
@michaelgrigoryan25 we can consider adding discord too in the future :)

**Pull request merged**
