### PR TITLE
feat: add check for updates on startup

### PR DESCRIPTION
**Pull request by Adity20**
The code changes add a new function `checkForUpdates()` that checks for updates on startup by making an API call to fetch the latest release information from GitHub. If a new version is available, it prompts the user to update to the latest version. The function also includes logic to handle user preferences for updates.

## Related Issue
  - https://github.com/keploy/keploy/issues/2071

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
I have added a new function checkForUpdates() that checks for updates on startup by making an API call to fetch the latest release information from GitHub. If a new version is available, it prompts the user to update to the latest version. The function also includes logic to handle user preferences for updates. This feature ensures users are notified of the latest version and can choose whether to update immediately or later, with their preferences saved for future reference.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Please let us know if any test cases are added
No

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Adity20** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Adity20** [comment]
@Swpn0neel I have created this pull request for the issue #2071 please check once

**Comment by Sonichigo** [comment]
@Adity20 the pipelines are failing: - https://github.com/keploy/keploy/pull/2097/checks . Please check them once

**Comment by Adity20** [comment]
@Sonichigo do i need to sign off every commit??
i'll have to redo the pr that means

**Comment by Swpn0neel** [comment]
> @Sonichigo do i need to sign off every commit?? i'll have to redo the pr that means

Yes! As your DCO is failing, you can try rebasing it:
1. Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
2. In your local branch, run: git rebase HEAD~3 --signoff
3. Force push your changes to overwrite the branch: git push --force-with-lease origin main

**Comment by jaiakash** [comment]
Hi @Adity20 I too have raised a similar PR (#2098). One suggestion from my side, you can use https://github.com/keploy/keploy/blob/55df9dc18bb1f1208ab7e57d5b7afea0900709a5/utils/utils.go#L313
function to check for latest version instead of rewriting from scratch. I hope it helps.

**Comment by Sonichigo** [comment]
@Adity20 not just DCO but build pipelines are also failing.

**Comment by Adity20** [comment]
I am redoing the PR. Some issue is still there .

**Pull request closed without merging**
