### PR TITLE
added FAQs to Keploy's Readme

### PR DESCRIPTION
**Pull request by yaten2302**
## Related Issue
 This PR adds FAQs to Keploy's readme.md file.
Fixes https://github.com/keploy/keploy/issues/2095

## Type of change

 - [x] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|          Updated           |
|:--------------------------:|
| <b>image </b> |

### CODE REVIEW

**Comment by yaten2302** [comment]
<b>*I have read the CLA Document and I hereby sign the CLA*

**Comment by shivamsouravjha** [comment]
image
for answers we can either use "-" or any other thing as its bit confusing as to which is the answer.

**Comment by yaten2302** [comment]
May I put a line gap in b/w the que and the answer or should I put "-", as you told?

**Comment by Swpn0neel** [comment]
It's better if you put the "-" too!

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Keep the 6th question on 2nd, just like the previous one!

**Comment by yaten2302** [comment]
Made the changes @Swpn0neel sir 👍

**Review by Swpn0neel — APPROVED** [review]

**Comment by Swpn0neel** [comment]
Fix the DCO check! @yaten2302

**Pull request merged**
