### PR TITLE
add python to utgen

### PR DESCRIPTION
**Pull request by s2terminal**
## What does this PR do?
I have added Python to `utgen` which is done by specifying `testDir`.

## Related PRs and Issues

- related: https://github.com/orgs/keploy/discussions/2466

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know test plan followed
I have verified that the following commands succeed using pytest-cov.

```
$ keploy gen \
  --testDir="./" \
  --coverageReportPath="./coverage.xml" \
  --testCommand="uv run pytest --cov ./ --cov-report xml" \
  --model="gpt-4o-mini"
```

I am still getting used to contributing to this repository. Please point out any other tests needed.

## Checklist:
- [x] Have you read the [Contributing Guidelines on issues](https://keploy.io/docs/keploy-explained/contribution-guide/)?
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by s2terminal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @s2terminal, thanks for creating the PR! I noticed that the test identifier used in your changes does not follow our standard convention. For Python, we use test_ as the prefix for test functions. Could you please update the test identifiers to follow this convention?

**Comment by s2terminal** [comment]
Thank you for your comment @Hermione2408 . [The official Pytest documentation](https://docs.pytest.org/en/stable/explanation/goodpractices.html#conventions-for-python-test-discovery) says to look for `test_*.py or *_test.py files`. I have checked the implementation of Keploy. It seems that Keploy only looks for test file patterns by suffix. It will take some time to modify Keploy so that it can also look for files by prefix.

**Comment by s2terminal** [comment]
@Hermione2408  I modified the test files so that they use both `*_test.py` and `test_*.py` as identifiers.
As a side effect of this modification, I reduced the amount of hard-coding of `.test`. I think this has reduced the number of bugs.

**Review by Hermione2408 — APPROVED** [review]
Thanks, @s2terminal ! Supporting both test_*.py and *_test.py aligns with Pytest standards and reduces hard-coding. LGTM!

**Pull request merged**
