### PR TITLE
[feature]: Added the time taken by test-set

### PR DESCRIPTION
**Pull request by Yaxhveer**
## Related Issue
  - Info about Issue or bug

Closes: #1826

#### Describe the changes you've made
Added time taken by each test-set in testReportVerdict struct. Currently magenta is being used for float64 in pp color scheme.
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Yaxhveer** [comment]
@Sarthak160 Please review the PR.

**Comment by Sarthak160** [comment]
@Yaxhveer Why not we used the same blue color to log time instead of magenta color ??

**Comment by Yaxhveer** [comment]
@Sarthak160 Currenly [here](https://github.com/keploy/keploy/blob/7e6c1388a6eaf26176526f41258adccae409ac08/pkg/models/const.go#L41) ,magenta color is defined for float types. Due you want it to be changed for every float or just for this case?

**Comment by Sarthak160** [comment]
> @Sarthak160 Currently [here](https://github.com/keploy/keploy/blob/7e6c1388a6eaf26176526f41258adccae409ac08/pkg/models/const.go#L41) ,magenta color is defined for float types. Due you want it to be changed for every float or just for this case?

Yes, for this case only I want them to be in uniform color.

**Comment by Sarthak160** [comment]
Hi @Yaxhveer, This is still logging time taken in magenta.

**Comment by Yaxhveer** [comment]
Hey @Sarthak160, currently my majors are ongoing would correct it by thursday.

**Comment by Yaxhveer** [comment]
Hey @Sarthak160, I changed the color to blue by updating the color for float. Though we could also use ansi colors codes but that does not work with preety printer so we would need to use fmt.Printf().

image

**Pull request closed without merging**
