### PR TITLE
update environment variable name for port of keploy server

### PR DESCRIPTION
**Pull request by Frey0-0**
Closes: #469 
Reference: [#62](https://github.com/keploy/typescript-sdk/pull/62)

#### Describe the changes you've made
Just change the name of the environment variable for the port of the Keploy server

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by nehagup — CHANGES_REQUESTED** [review]
I think this will be a breaking change for existing users. Also, change is also required where this env variable is being read.

**Comment by Sarthak160** [comment]
I guess , This we already have an alternative for this problem . @Frey0-0 Since we are using [envconfig](https://pkg.go.dev/github.com/kelseyhightower/envconfig@v1.4.0) library for managing env variables , You can simply use `KEPLOY_PORT` env variable to set your custom keploy port as it has more priority than `PORT` env variable. 
Similarly you can prefix `KEPLOY_`  with any other keploy env variable available in the config.

**Comment by Frey0-0** [comment]
Hey @Sarthak160 @nehagup, Actually if a person doesn't use the variable `KEPLOY_PORT` and they are using the variable `PORT` in their project's because it is so common and source it then the keploy server will also try to run on the same port as that of the app. I was actually trying to solve another issue where we start the keploy server automatically so @re-Tick encountered this issue while reviewing so if we change the variable name from env even if a person uses PORT it will still be default 6789 unless they mention `KPORT.`
I might be wrong( most probably am) but the variable name read everywhere is still `Port` of the `config` struct, just variable name it is mapped to in the env will be `KPORT`. It is not a breaking change :sweat_smile: I used the dev docker version mentioned in the repo. Please tell me if I am wrong and what else can be a better solution to this :smile:

**Comment by Sarthak160** [comment]
Hey @Frey0-0 , Can you please try by using `KEPLOY_PORT` env variable for keploy's port and `PORT` env variable for your own application . I think this should work and should not overlap the keploy's own port .

**Comment by Sarthak160** [comment]
Hey @Frey0-0 , Can you please try by using `KEPLOY_PORT` env variable for keploy's port and `PORT` env variable for your own application . I think this should work and should not overlap the keploy's own port .

**Comment by Frey0-0** [comment]
@Sarthak160 I know that :sweat_smile: but it is for a user who is just using keploy and has no idea of the internals. I didn't face this problem actually @re-Tick was trying a change I made for an issue in typescript-sdk and faced this issue :sweat_smile: so I raised it.

**Comment by re-Tick** [comment]
@Sarthak160 let me try the changes. Maybe we don't require a "KPORT".

**Comment by re-Tick** [comment]
@Frey0-0 I have tried using KEPLOY_PORT env variable while running keploy from TS-SDK in your changes. And it works. Please close this PR.

**Pull request closed without merging**
