### PR TITLE
chore: colorise logo 

### PR DESCRIPTION
**Pull request by shivamsouravjha**
Fixed: https://github.com/keploy/keploy/issues/1579

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
@Sarthak160 please review

**Comment by Sarthak160** [comment]
@shivamsouravjha Was disable-ansi flag meant to disable all other ansi colors like testcase passed (green) failed (red) or just logo color ??

**Comment by shivamsouravjha** [comment]
it is an existing feature and disable all the colors.

**Review by Sarthak160 — APPROVED** [review]
LGTM

**Review by Sarthak160 — APPROVED** [review]
LGTM!

**Pull request merged**
