### PR TITLE
fix: generate config returns after logging error

### PR DESCRIPTION
**Pull request by officialasishkumar**
## Related Issue
  The implementation of `keploy/pkg/service/generateConfig/generateConfig.go` doesn't return in case of error and is subject to nil memory exception.

Closes: #1152

#### Describe the changes you've made
Added return 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by shivamsouravjha — COMMENTED** [review]
Try installing go extension and fix the code style. The return terminology isn't right(set code style update)

**Comment by officialasishkumar** [comment]
Hey @shivamsouravjha, can you please review this?

**Review by shivamsouravjha — COMMENTED** [review]
* Quick note on the logging strategy in the code: When we use a logger at the 'fatal' level, the code execution halts automatically at that point. Hence, adding return statements after each 'fatal' logger isn't necessary.

* Also, on choosing between 'Error' and 'Fatal' for logging: 'Fatal' should be used in situations where the application must stop immediately due to a critical issue. This ensures immediate attention to severe problems and prevents the continuation of processes that could be harmful

**Comment by shivamsouravjha** [comment]
cc @charankamarapu

**Comment by shivamsouravjha** [comment]
@officialasishkumar are you working on this issue

**Comment by officialasishkumar** [comment]
I've made the necessary changes. Please take a look @shivamsouravjha

**Review by shivamsouravjha — APPROVED** [review]
LGTM

**Review by shivamsouravjha — COMMENTED** [review]
reformat the code as formatting isssue

**Comment by officialasishkumar** [comment]
@shivamsouravjha PTAL

**Review by shivamsouravjha — APPROVED** [review]

**Comment by shivamsouravjha** [comment]
@officialasishkumar congratulations on the PR merge!

**Pull request merged**
