### PR TITLE
readme_updated 

### LINKED ISSUE #113: update in the readme file
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There are two 'your' in the read me file

Screenshot from 2022-04-16 17-34-22

### PR DESCRIPTION
**Pull request by Akshit42-hue**
Signed-off-by: Axit Patel <patelakshit2025@gmail.com>

Fixes #113

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
Please do have a look @nehagup

**Review by nehagup — APPROVED** [review]
Good catch!

**Comment by nehagup** [comment]
@Akshit42-hue Please add yourselves [here](https://github.com/keploy/keploy#-our-valuable-contributors-), and I shall merge this PR

**Comment by Akshit42-hue** [comment]
done @nehagup

**Pull request merged**
