### PR TITLE
feat: mock data compress-decompress

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
## Related Issue
- Closes: #184
Compressed the data on Encode wiriting mocks into yaml and decompressed on Decode

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)
 Screenshot from 2022-10-17 11-33-45

### CODE REVIEW

**Comment by Shivansh-yadav13** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by slayerjain** [comment]
@Sarthak160 @re-Tick please review

**Comment by Sarthak160** [comment]
Hi @Shivansh-yadav13 . Are you still working on this part ??  I was trying to run my application on test mode after recording few tests and It was showing below stacktrace - 

```
 ERROR   regression/regression.go:145    unexpected EOF
go.keploy.io/server/pkg/service/regression.(*Regression).ReadTCS
        /Users/sarthak_1/Documents/Keploy/final/keploy/pkg/service/regression/regression.go:145
go.keploy.io/server/http/regression.(*regression).GetTCS
        /Users/sarthak_1/Documents/Keploy/final/keploy/http/regression/regression.go:177
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70
github.com/go-chi/chi.(*Mux).Mount.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70
github.com/go-chi/chi.(*Mux).Mount.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70
github.com/go-chi/chi.(*Mux).Mount.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/cors.(*Cors).Handler.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/cors@v1.2.0/cors.go:228
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/keploy/go-sdk/integrations/kchi.(*chiV5).Next
        /Users/sarthak_1/go/pkg/mod/github.com/keploy/go-sdk@v0.6.3/integrations/kchi/chi-v5.go:64
github.com/keploy/go-sdk/keploy.Middleware
        /Users/sarthak_1/go/pkg/mod/github.com/keploy/go-sdk@v0.6.3/keploy/router.go:30
github.com/keploy/go-sdk/integrations/kchi.ChiMiddlewareV5.func1.1
        /Users/sarthak_1/go/pkg/mod/github.com/keploy/go-sdk@v0.6.3/integrations/kchi/chi-v5.go:13
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:87
net/http.serverHandler.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2947
net/http.(*conn).serve
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:1991
2022-10-17T15:20:11.879+0530    ERROR   regression/regression.go:128    unexpected EOF
go.keploy.io/server/pkg/service/regression.(*Regression).StartTestRun
        /Users/sarthak_1/Documents/Keploy/final/keploy/pkg/service/regression/regression.go:128
go.keploy.io/server/http/regression.(*regression).Start
        /Users/sarthak_1/Documents/Keploy/final/keploy/http/regression/regression.go:94
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70
github.com/go-chi/chi.(*Mux).Mount.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70
github.com/go-chi/chi.(*Mux).Mount.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).routeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/cors.(*Cors).Handler.func1
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/cors@v1.2.0/cors.go:228
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/keploy/go-sdk/integrations/kchi.(*chiV5).Next
        /Users/sarthak_1/go/pkg/mod/github.com/keploy/go-sdk@v0.6.3/integrations/kchi/chi-v5.go:64
github.com/keploy/go-sdk/keploy.Middleware
        /Users/sarthak_1/go/pkg/mod/github.com/keploy/go-sdk@v0.6.3/keploy/router.go:30
github.com/keploy/go-sdk/integrations/kchi.ChiMiddlewareV5.func1.1
        /Users/sarthak_1/go/pkg/mod/github.com/keploy/go-sdk@v0.6.3/integrations/kchi/chi-v5.go:13
net/http.HandlerFunc.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2109
github.com/go-chi/chi.(*Mux).ServeHTTP
        /Users/sarthak_1/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:87
net/http.serverHandler.ServeHTTP
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:2947
net/http.(*conn).serve
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:1991
```
It's unable to fetch testcases , I tried to debug and found that it is unable to read  data during unzipping 
 `data, err := ioutil.ReadAll(gzr)`

**Comment by Sarthak160** [comment]
Hey @Shivansh-yadav13 I have fixed this for test mode you can refer that and make changes in your branch

**Comment by Shivansh-yadav13** [comment]
@Sarthak160 should I close this PR?

**Comment by Sarthak160** [comment]
> @Sarthak160 should I close this PR?

Or you can just add changes in your branch , I made a separate branch coz I didn't have access to your repo 🙂

**Comment by Sarthak160** [comment]
@Shivansh-yadav13  can you please sign the DCO ?

**Review by slayerjain — APPROVED** [review]
LGTM. Thanks for the contribution @Shivansh-yadav13

**Pull request merged**
