### PR TITLE
feat: add support for mocking kube controller

### PR DESCRIPTION
**Pull request by shivamsouravjha**
## Related Issue
  - Info about Issue or bug

Closes: #1320

#### To Record your controller with keploy follow:

1. Set your `cfg.Insecure = true` and `cfg.CAFile = ""` for your Kubernetes `*rest.Config` object.
2. Create a custom `RoundTripper` to add a header field containing  [resource version](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes), This can be treated as a trace-id to match your requests during that same state with your recorded mocks. You can also refer the illustration [here](https://github.com/Sarthak160/sample-controller/blob/44c078e4d0646b06e7a5befbbfac54532b693c9c/main.go#L46). For example:
   **Implementation of custom round tripper** - 
   ```go
   func (crt *customRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	ctx := req.Context()
	rsv := ctx.Value("ResourceVersion")

	if rsv !=nil {
		req.Header.Add("keploy-header", rsv.(string))
	}
	return crt.rt.RoundTrip(req)
    }
   ```
   
    ```go
    cfg.WrapTransport = func(rt http.RoundTripper) http.RoundTripper {
        return &customRoundTripper{rt: rt}
    }
    ```

3. Ensure to set the resource version value in `context.Context` during the sync process. This is crucial for passing the modified context to the update and create methods of your controller. This needs to be done to get the value of resource version from the context and add it to request header in your RoundTripper created above. For eg - 
```go
    func (c *Controller) syncHandler(ctx context.Context, key string) error {
	....
	// set ResourceVersion in ctx
	rv := foo.GetResourceVersion()
	if rv!= "" {
		ctx = context.WithValue(ctx, "ResourceVersion", rv)
	}
    }
    ....
```
 **passing the context to your controller methods**
```go 
	deployment, err = c.kubeclientset.AppsV1().Deployments(foo.Namespace).Create(ctx, newDeployment(foo), metav1.CreateOptions{})
	
	deployment, err = c.kubeclientset.AppsV1().Deployments(foo.Namespace).Update(ctx, newDeployment(foo), metav1.UpdateOptions{})
```
5. Build the go binary of your k8s controller. For example:
    ```shell
    go build -o sample-controller .
    ```
6. To record the outgoing calls via keploy, wrap your command to run controller with keploy’s. Add the following flags `--mtls-cert-path`, `--mtls-key-path` and `--mtls-host-name` according to your kube config respectively:

```shell 
sudo -E env PATH=$PATH keploy record -c "./sample-controller -kubeconfig=$HOME/.kube/config"  --mtls-cert-path "$HOME/.minikube/profiles/minikube/client.crt" --mtls-key-path "$HOME/.minikube/profiles/minikube/client.key"  --mtls-host-name 192.168.49.2:8443
```
7. You can see `keploy/test-set-0/mocks.yaml` created as soon as keploy starts intercepting the outbound calls.

8. Each resource version has separate mock file denoted with `mocks_ + "<resource_version>"`.

#### To test your controller with recorded mocks:-

1. Run test mode of keploy with mockAssert flag as true with your controller binary, you don't need to provide the kube config file as keploy will automatically create a fake one for you (Currently keploy creates dummy config for minikube only). Later keploy can also create a dummy client keys and cert paths for generating fake kube config files.

```shell
sudo -E env PATH=$PATH  keploy test -c "<go-binary-of-controller-app>" --mockAssert true
``` 

2. You can explicitly set your own repay time which will try to replay your recorded session within the provided time . It's like watching your favourite movie at 2x speed 🍿. Here time input is taken in seconds. 
```shell
 keploy test -c <go-binary-of-controller-app> --mockAssert true --replaySession 100
```
3. **Note** - The above part is done by trimming the large enough event time gap to a precise average duration between the two events of the informers. As controller will start making all the related calls for a particular resource when the informer will bookmark and start to watch for that new resource version. In this way we are able to send those events earlier than it occurred in record.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Sarthak160** [comment]
@shivamsouravjha Please check the failing build .

**Comment by slayerjain** [comment]
Please fix the race condition in the TLS certificate logic: 

```
==================
WARNING: DATA RACE
Write at 0x000001bac130 by goroutine 47:
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:740 +0xa0
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Previous write at 0x000001bac130 by goroutine 48:
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:740 +0xa0
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Goroutine 47 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8

Goroutine 48 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8
==================
==================
WARNING: DATA RACE
Write at 0x000001bab3e0 by goroutine 47:
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:745 +0x2a8
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Previous write at 0x000001bab3e0 by goroutine 48:
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:745 +0x2a8
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Goroutine 47 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8

Goroutine 48 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8
==================
==================
WARNING: DATA RACE
Write at 0x000001bac140 by goroutine 47:
  go.keploy.io/server/pkg/proxy.certForClient()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:495 +0x5c
  crypto/tls.(*Config).getCertificate()
      /usr/local/go/src/crypto/tls/common.go:1116 +0xb4
  crypto/tls.(*serverHandshakeStateTLS13).pickCertificate()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:435 +0x600
  crypto/tls.(*serverHandshakeStateTLS13).handshake()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:59 +0x58
  crypto/tls.(*Conn).serverHandshake()
      /usr/local/go/src/crypto/tls/handshake_server.go:53 +0x168
  crypto/tls.(*Conn).serverHandshake-fm()
      <autogenerated>:1 +0x44
  crypto/tls.(*Conn).handshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1552 +0x3f0
  crypto/tls.(*Conn).HandshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1492 +0x658
  crypto/tls.(*Conn).Handshake()
      /usr/local/go/src/crypto/tls/conn.go:1476 +0x644
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:759 +0x640
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Previous write at 0x000001bac140 by goroutine 48:
  go.keploy.io/server/pkg/proxy.certForClient()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:495 +0x5c
  crypto/tls.(*Config).getCertificate()
      /usr/local/go/src/crypto/tls/common.go:1116 +0xb4
  crypto/tls.(*serverHandshakeStateTLS13).pickCertificate()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:435 +0x600
  crypto/tls.(*serverHandshakeStateTLS13).handshake()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:59 +0x58
  crypto/tls.(*Conn).serverHandshake()
      /usr/local/go/src/crypto/tls/handshake_server.go:53 +0x168
  crypto/tls.(*Conn).serverHandshake-fm()
      <autogenerated>:1 +0x44
  crypto/tls.(*Conn).handshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1552 +0x3f0
  crypto/tls.(*Conn).HandshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1492 +0x658
  crypto/tls.(*Conn).Handshake()
      /usr/local/go/src/crypto/tls/conn.go:1476 +0x644
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:759 +0x640
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Goroutine 47 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8

Goroutine 48 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8
==================
==================
WARNING: DATA RACE
Write at 0x000001a71fa0 by goroutine 47:
  go.keploy.io/server/pkg/proxy.certForClient()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:497 +0xa8
  crypto/tls.(*Config).getCertificate()
      /usr/local/go/src/crypto/tls/common.go:1116 +0xb4
  crypto/tls.(*serverHandshakeStateTLS13).pickCertificate()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:435 +0x600
  crypto/tls.(*serverHandshakeStateTLS13).handshake()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:59 +0x58
  crypto/tls.(*Conn).serverHandshake()
      /usr/local/go/src/crypto/tls/handshake_server.go:53 +0x168
  crypto/tls.(*Conn).serverHandshake-fm()
      <autogenerated>:1 +0x44
  crypto/tls.(*Conn).handshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1552 +0x3f0
  crypto/tls.(*Conn).HandshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1492 +0x658
  crypto/tls.(*Conn).Handshake()
      /usr/local/go/src/crypto/tls/conn.go:1476 +0x644
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:759 +0x640
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Previous read at 0x000001a71fa0 by goroutine 48:
  github.com/cloudflare/cfssl/log.print()
      /home/shubham.linux/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.4/log/log.go:66 +0x38
  github.com/cloudflare/cfssl/log.outputf()
      /home/shubham.linux/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.4/log/log.go:89 +0x5c
  github.com/cloudflare/cfssl/log.Debugf()
      /home/shubham.linux/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.4/log/log.go:156 +0xbc
  github.com/cloudflare/cfssl/csr.(*KeyRequest).Generate()
      /home/shubham.linux/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.4/csr/csr.go:69 +0x64
  github.com/cloudflare/cfssl/csr.ParseRequest()
      /home/shubham.linux/go/pkg/mod/github.com/cloudflare/cfssl@v1.6.4/csr/csr.go:227 +0x1e0
  go.keploy.io/server/pkg/proxy.certForClient()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:508 +0x1e0
  crypto/tls.(*Config).getCertificate()
      /usr/local/go/src/crypto/tls/common.go:1116 +0xb4
  crypto/tls.(*serverHandshakeStateTLS13).pickCertificate()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:435 +0x600
  crypto/tls.(*serverHandshakeStateTLS13).handshake()
      /usr/local/go/src/crypto/tls/handshake_server_tls13.go:59 +0x58
  crypto/tls.(*Conn).serverHandshake()
      /usr/local/go/src/crypto/tls/handshake_server.go:53 +0x168
  crypto/tls.(*Conn).serverHandshake-fm()
      <autogenerated>:1 +0x44
  crypto/tls.(*Conn).handshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1552 +0x3f0
  crypto/tls.(*Conn).HandshakeContext()
      /usr/local/go/src/crypto/tls/conn.go:1492 +0x658
  crypto/tls.(*Conn).Handshake()
      /usr/local/go/src/crypto/tls/conn.go:1476 +0x644
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleTLSConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:759 +0x640
  go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:849 +0x1c70
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:583 +0xec

Goroutine 47 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8

Goroutine 48 (running) created at:
  go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:580 +0x7b8
  go.keploy.io/server/pkg/proxy.BootProxy.func1()
      /Users/shubham/projects/keploy/keploy/pkg/proxy/proxy.go:430 +0xa8
==================
I0117 13:13:40.601393  245713 controller.go:240] "Successfully synced" resourceName="default/example-foo"
```

**Comment by slayerjain** [comment]
@Sarthak160 @shivamsouravjha don't we need to pass the ctx here too? 

https://github.com/Sarthak160/sample-controller/blob/44c078e4d0646b06e7a5befbbfac54532b693c9c/pkg/generated/informers/externalversions/samplecontroller/v1alpha1/foo.go#L65

**Comment by charankamarapu** [comment]
Hey @shivamsouravjha what is the progress of this PR..? should we close or is it work in progress..? or will it get resolved by refactor..?

**Comment by re-Tick** [comment]
Closing this, since the changes should be updated according to the refactored changes of main.

**Pull request closed without merging**
