### PR TITLE
Feature/pass count with list of test cases

### PR DESCRIPTION
**Pull request by anirudhjain75**
## Related Issue
  - Implement Pagination

Closes: Part of #3

#### Describe the changes you've made
I have included count in the testCase query and renamed it to testCases. This is done using CountDocuments call using the same filters except the count. Updated the schema to use an Object instead of just a List.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by anirudhjain75** [comment]
Frontend Implementation in https://github.com/keploy/ui/pull/67

**Review by Sarthak160 — APPROVED** [review]
Looks good ! Clean approach

**Comment by slayerjain** [comment]
@anirudhjain75 this mostly looks good, but how about we follow the specs mentioned on the graphql docs? - https://graphql.org/learn/pagination/#connection-specification

Please go through the article above the specification section too :)

**Comment by slayerjain** [comment]
@anirudhjain75 also please look at the failing tests

**Comment by nehagup** [comment]
Thanks for the PR @anirudhjain75. While this was a good approach, we found an approach where the schema changes were not required and using the beauty of GraphQL within the same complexity we were able to fetch the total number of records. Closing this one as this is resolved now. :)

PR https://github.com/keploy/ui/pull/68

**Pull request closed without merging**
