### PR TITLE
Change Unique Key of Map to testCasePath

### PR DESCRIPTION
**Pull request by Frey0-0**
## Related Issue
Currently Apps having same name or appID were considered the same and test case indexing was same for both of them because they weren't unique according to the `tcsCount` map

Closes: #303 

#### Describe the changes you've made
I have simply changed the key of the tcsCount map from the app name to the testCasePath which will always be unique for very app as they will always be present in different directories even if they have the same name.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| Screenshot from 2023-03-11 23-13-20 | <b>
Screenshot from 2023-03-11 22-48-24
</b> |

### CODE REVIEW

**Comment by Frey0-0** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by re-Tick** [comment]
LGTM

**Review by re-Tick — APPROVED** [review]

**Comment by Frey0-0** [comment]
@re-Tick hey, someone on slack mentioned that if a PR is done then certain tags will be given to the PR so when does that happen exactly? :sweat_smile:

**Comment by re-Tick** [comment]
Let me add them.

**Comment by Frey0-0** [comment]
Thank you :heart:

**Comment by Sarthak160** [comment]
This PR is stale since we migrated to V2 which has newer code structure in which testcases are segregated in different test sets according to the `record mode` session .

**Pull request closed without merging**
