### PR TITLE
Fix grpc

### PR DESCRIPTION
**Pull request by re-Tick**
## Related Issue
  -  Changes in the GetTCS of `v0.8.2` returns testcases irrespective due to which go-sdk versions before `0.8.2` fetches the same set of tcs twice resulting in the error `unlock of unlocked mutex`. 
  
Closes: #500
#### Describe the changes you've made
Makes the `reqType` query param as optional. This will return testcases of same type when `reqType` is not empty and all tcs if `reqType` param is empty
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by aerowisca** [comment]
Why are switching to a generic string for `tcsType` when we already made the effort to switch to a more stable and predictable [models.Kind](https://github.com/keploy/keploy/blob/bb7dd253b5c90056a1d145835d59094a8dd30d00/pkg/models/mock.go#L22)? IMO, it's better to modify the signature to accept a `models.Kind` and in our handler, we do a sanity test on whether the given request parameter fits into one of the known models.

Also, we don't need to do the filtering after unnecessarily collecting a large number of results and sorting them. You can instead modify the function signature for [toTestCase](https://github.com/keploy/keploy/blob/bb7dd253b5c90056a1d145835d59094a8dd30d00/pkg/platform/fs/mock.go#L151) so that results are [filtered](https://github.com/keploy/keploy/blob/bb7dd253b5c90056a1d145835d59094a8dd30d00/pkg/platform/fs/mock.go#L69) even before they are sorted.

**Comment by re-Tick** [comment]
These changes are made to maintain the backward compatibility with older go-sdk versions. 
 
 That can be good but since, the reqType is used to filter the array of testcases only, it is not needed to sanitise.

**Review by Sarthak160 — APPROVED** [review]
LGTM 😇

**Comment by slayerjain** [comment]
LGTM

**Pull request merged**
