### PR TITLE
Modify GetAll API of testCaseDB to return all entries instead of considering index and limit

### PR DESCRIPTION
**Pull request by anirudhjain75**
## Related Issue
https://github.com/keploy/ui/issues/24 /testlist testcases part

Closes: NA

#### Describe the changes you've made

Removed limit and offset consideration of getAll for testcasedb. Therefore allowing pagination to be handled on client side.

Added ToDo comment for future purpose.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

None

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
My code generates warning as I added a ToDo comment for future reference.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)
NA

### CODE REVIEW

**Comment by nehagup** [comment]
@anirudhjain75 How about we keep 1K limit on the frontend and not change the backend implentation?

**Comment by anirudhjain75** [comment]
Hmm. Then what about the times when there are more than 1k testcases ?

**Comment by anirudhjain75** [comment]
@nehagup 

Here are the drawbacks with implementation

Handling pagination on Server -> Requires amount of total item exist for particular fitler
*Handling pagination on Client -> Requires all the entries in client so the count and pages are automatically configured.

* - Implemented by this PR

Incase the req input size is set to 1000, The pagination can be made to work correctly but the count displayed in pagination part of DataGrid would be wrong.

A better solution would be updating the server to send PageSize data with App data with getTc API which currently only sends a list of testcases.

Possible implication of this would be that an extra query is run on database to get the number of testCases of an App.

**Comment by nehagup** [comment]
Thanks for the PR @anirudhjain75. While this was a good approach, we found an approach where the schema changes were not required and using the beauty of GraphQL within the same complexity we were able to fetch the total number of records. Closing this one as this is resolved now. :)

PR https://github.com/keploy/ui/pull/68

**Pull request closed without merging**
