### PR TITLE
[BUG]: Added check for detach mode

### PR DESCRIPTION
**Pull request by Yaxhveer**
## Related Issue
  - Info about Issue or bug

Closes: #1645 

#### Describe the changes you've made
Added check for detach mode in docker command.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Yaxhveer** [comment]
@charankamarapu Please review the changes.

**Comment by charankamarapu** [comment]
Hey @Yaxhveer we have refactored the main code base. But the docker related testing is not yet done. We will notify you once that is done and then we continue with the PR.

**Comment by Yaxhveer** [comment]
@charankamarapu PR is updated according to the refactored codebase. Kindly review the PR

**Comment by charankamarapu** [comment]
Changes look fine please add the screenshot of the result.

**Comment by Yaxhveer** [comment]
cmd: ```keployV2 record -c "docker compose up -d" --containerName "ginMongoApp"```

image

**Comment by re-Tick** [comment]
LGTM, Merging the PR into main.

**Review by re-Tick — APPROVED** [review]

**Pull request merged**
