### PR TITLE
fix(cmd): disable cobra default completion cmd

### PR DESCRIPTION
**Pull request by dreamjz**
## Related Issue
Closes: #1116

#### Describe the changes you've made
Disable cobra default completion command

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |
|image|image|

### CODE REVIEW

**Comment by dreamjz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by PranshuSrivastava** [comment]
Hey @dreamjz the PR is correct and fixes the issue. Could you just complete the DCO check before I merge it? You can see how to pass it by clicking on the Details button.

**Comment by dreamjz** [comment]
OK

**Review by PranshuSrivastava — APPROVED** [review]
LGTM

**Pull request merged**
