### PR TITLE
docker refactor

### PR DESCRIPTION
**Pull request by shivamsouravjha**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by slayerjain** [comment]
@shivamsouravjha please update the newly added tag to the go build command to GitHub CI and also docs

**Comment by shivamsouravjha** [comment]
@slayerjain added the tag for node, go and python in related workflow files.

**Comment by charankamarapu** [comment]
Please fix the docker related github actions according to the changes done for docker.

**Comment by charankamarapu** [comment]
Looks like golang on linux is failing due to unable to kill the application. Please check that too.

**Comment by himanshu-wedensday** [comment]
@gouravkrosx please merge this pr as it has fixes that is stopping keploy to run in docker @nehagup FYI

**Comment by shivamsouravjha** [comment]
https://github.com/keploy/keploy/issues/1725 solves

**Review by gouravkrosx — APPROVED** [review]
LGTM

**Pull request merged**
