### PR TITLE
[fix]: update keploy even it has the latest version

### PR DESCRIPTION
**Pull request by AhmedLotfy02**
## Related Issue
  - Keploy update it's version even it has the latest one

Closes: #1608

#### Describe the changes you've made
- Just remove "v" from the release tag to be the same format of what we get from binary, example v2.x.x --> 2.x.x.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by charankamarapu** [comment]
Hi @AhmedLotfy02 we refactored the main branch . But the updated feature has been not completely tested with the refactoring . We will working on it asap once that is done we can proceed with this PR.

**Comment by AhmedLotfy02** [comment]
@charankamarapu Hi, it's fixed in the refactored v2 by adding "v" prefix to version as in the screenshot provided


DeepinScreenshot_select-area_٢٠٢٤٠٣١٥٠٢٠٢١٩

**Comment by shivamsouravjha** [comment]
hey @AhmedLotfy02 can you fix the conflict error

**Comment by AhmedLotfy02** [comment]
@shivamsouravjha I think we could close this PR as the desired output is done on the latest version.
image

**Comment by shivamsouravjha** [comment]
Closing this as error is already solved

**Pull request closed without merging**
