### PR TITLE
Updated install script to install a specific version of curl Signed-o…

### PR DESCRIPTION
**Pull request by Redarcher9**
…ff-by: Snehit Paunikar <snehit.86@gmail.com>

## Related Issue
  - Info about Issue or bug

Closes: [#1958]

#### Describe the changes you've made
Added logic to install a specific version of keploy through CURL command. 
Usage 

`curl --silent -O -L https://keploy.io/install.sh && source install.sh -v v2.1.0-alpha28
`
This curl command will install version v2.1.0-alpha28.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added
NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Redarcher9** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Redarcher9** [comment]
recheck

**Comment by gouravkrosx** [comment]
@Redarcher9, It's not working and showing: ```install.sh:11: parse error near `)'```

**Comment by Redarcher9** [comment]
Hi @gouravkrosx ,

Can you tell me how do I test it in local? Will running keploy.sh script directly do it?

**Comment by gouravkrosx** [comment]
@Redarcher9 , you can remove the last step where we are removing the script after its execution  in the install.sh file and then try running `source install.sh -v v2.1.0-alpha28` where install.sh is your updated script.

**Comment by gouravkrosx** [comment]
Already closed by https://github.com/keploy/keploy/pull/1993

**Pull request closed without merging**
