### PR TITLE
added ideas for generating new testcases from api schema and response

### PR DESCRIPTION
**Pull request by kartikvirendrar**
## Related Issue
  - Info about Issue or bug

Related to: #338 

#### Describe the changes you've made
Proposed few ideas for "generating new test cases using api schema and response provided" and sample codes for generating new testcases for api validating user email and password which returns JWT token for valid credentials.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added
NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by kartikvirendrar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nehagup** [comment]
@kartikvirendrar can you please write a brief on the solution you've proposed?

**Comment by kartikvirendrar** [comment]
I have added some sample test cases and description of my proposed solution, can you please check once

**Review by nehagup — COMMENTED** [review]
@kartikvirendrar according to the issue https://github.com/keploy/keploy/issues/338 the input for the test-case generator will be an API schema or an API call evoking the same path and for that the output should be some test-files generated using methodologies like BV, combinatorial, ML, RandomGeneration etc...

**Comment by charankamarapu** [comment]
Adding to what @nehagup commented - This task is majorly to prepare a sort of design where you include how do we convert schemas into auto generated tests . You must include how you intake schemas , how you will implement them to create tests . I have reviewed you ideas but they are a bit more specific to a type because in those examples you have used username and password as an example but lets say if you have a json object instead of username(string) how do you deal with that . In those examples you have hardcoded the tests but requirement is that we should be generating the tests . Below are few points you must more stress on
1. How do we take schema from the user and load in Keploy.
2. How do we convert that schema and produce automated tests which has almost every possible testcase.
3. How do we show the test cases generated to user . Like do we directly record(Keploy's record feature) these testcases which are generated .
4. What techniques we use for generating tests ? example : Swarm testing.

You ideas are good but these are too generic . I mean there are many techniques available which uses the same ideas you have proposed and also does many other things which improve the E2E testing . Try to do a bit of search regarding these.

This task is more kind of design thing with a bit of generic code .

**Comment by kartikvirendrar** [comment]
Ok, will work on it

**Comment by kartikvirendrar** [comment]
Hello mentors, I was not able to work on contribution in last week but now I want to resume working on it.
I am trying to run the echo-sql app but I am getting this error:
```
keploy 0.8.1

.2023-03-22T21:55:49.341-0400   INFO    server/server.go:215    keploy started at port 6789
2023-03-22T21:56:38.137-0400    INFO    testCase/testCase.go:228
💾 Recorded testcase with name: test-3 in yaml file at path: /home/kali/Desktop/KEPLOY/samples-go/echo-sql/keploy/tests

2023-03-22T21:56:38.137-0400    INFO    testCase/testCase.go:238
💾 Recorded mocks for testcase with name: test-3 at path: /home/kali/Desktop/KEPLOY/samples-go/echo-sql/keploy/mocks

failed to send testcase to backend      {"url": "/api/regression/testcase", "error": "Post \"http://localhost:6790/api/regression/testcase\": dial tcp [::1]:6790: connect: connection refused"}
github.com/keploy/go-sdk/keploy.(*Keploy).put
        /Users/runner/go/pkg/mod/github.com/keploy/go-sdk@v0.7.9/keploy/keploy.go:603
failed to send testcase to backend      {"url": "/api/regression/denoise", "error": "Post \"http://localhost:6790/api/regression/testcase\": dial tcp [::1]:6790: connect: connection refused"}
github.com/keploy/go-sdk/keploy.(*Keploy).put
        /Users/runner/go/pkg/mod/github.com/keploy/go-sdk@v0.7.9/keploy/keploy.go:603
```
can you please help

**Comment by kartikvirendrar** [comment]
Thankyou @aerowisca, it worked

**Comment by kartikvirendrar** [comment]
I have updated the README can you please check once

**Comment by charankamarapu** [comment]
closing the PR due to inactivity from author

**Pull request closed without merging**
