### PR TITLE
feat(grpc): make gRPC server for connection with SDKs

### PR DESCRIPTION
**Pull request by Sarthak160**
## Related Issue
  - #104 

#### Describe the changes you've made
- Created a gRPC server with protobuf for communication between SDKs .
- Add cmux router to multiplex connections based Http and gRPCs and enable them on the same port .  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by slayerjain** [comment]
@Sarthak160 please update the test cases and the pipelines

**Comment by Sarthak160** [comment]
@slayerjain coverage is increased above 75% .  Can we merge this PR  as it's being used as gRPC server for Java sdk ?

**Comment by slayerjain** [comment]
@Sarthak160 sure

**Review by slayerjain — APPROVED** [review]
LGTM

**Pull request merged**
