### PR TITLE
Introducing Keploy Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Keploy Guru](https://gurubase.io/g/keploy) to Gurubase. Keploy Guru uses the data from this repo and data from the [docs](https://keploy.io/docs/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Keploy Guru", which highlights that Keploy now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Keploy Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by kursataktas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Sonichigo** [comment]
hi @kursataktas, i tried the Gurubase and was impressed with the response. I have few question although -

1. Is Gurubase also OpenSource, if not what would be the pricing?
2. Would the data be always upto date from Keploy Docs and GitHub and can we add more sources?

**Comment by kursataktas** [comment]
Hey @Sonichigo 
Thanks for the review. Here are my answers:

1. Gurubase is not an open-source project, nor is it a commercial project at this time.
2. We are currently developing an admin panel where maintainers can view and edit the sources their "guru" uses to generate answers. We will also introduce a change detection feature that will refresh the sources whenever any are modified or a new version is released. Would you like me to update you once it’s available?

**Comment by kursataktas** [comment]
Hey @Sonichigo, is there any update on this?

**Comment by Hermione2408** [comment]
Hey @Sonichigo, it looks like @kursataktas followed up with some details on Guruba. Can you please check?

**Comment by Sonichigo** [comment]
Hi @kursataktas thanks for an update! Yes, i would be interested to know once admin panel is available! Excited to be a initial adopter of Gurubase.

**Pull request closed without merging**
