### PR TITLE
fix: check `errReadRespBody != nil` but return a nil value error `err`

### PR DESCRIPTION
**Pull request by alingse**
## What does this PR do?

fix a bug

btw, there should add a `defer httpResp.Body.Close()` 

## Related PRs and Issues

I create a linter to detect code that returns a non-relevant nilness error bug. I checked the top 1000 GitHub Go repositories and found this, all result listed in https://github.com/alingse/sundrylint/issues/4

Closes: #[issue number that will be closed through this PR]

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know test plan followed

Please describe the tests(if any). Provide instructions how its affecting the coverage.

## Checklist:
- [x] Have you read the [Contributing Guidelines on issues](https://keploy.io/docs/keploy-explained/contribution-guide/)?
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by alingse** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shivamsouravjha** [comment]
Hey @alingse the linter pipeline is breaking, please fix the same!

**Comment by alingse** [comment]
> Hey @alingse the linter pipeline is breaking, please fix the same!

ok, I will fix it later(after work)

**Review by shivamsouravjha — APPROVED** [review]
the linter is failing perhaps running gofmt can fix it

**Pull request merged**
