### PR TITLE
docs: use dynamic contributors list

### PR DESCRIPTION
**Pull request by burntcarrot**
## Related Issue
See https://github.com/keploy/keploy/pull/101#issuecomment-1086548839.

#### Describe the changes you've made
Used [contrib.rocks](https://contrib.rocks) to dynamically generate the list of contributors.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by burntcarrot** [comment]
It's a very tiny contribution - but I believe that it would save us a lot of time from manually adding contributors.

**Comment by Ayush7614** [comment]
@burntcarrot i am already use this one but @nehagup told me to add all contributers manullay that`s why i am adding one by one contributers manually

**Comment by nehagup** [comment]
> It's a very tiny contribution - but I believe that it would save us a lot of time from manually adding contributors.

@burntcarrot In the contributors list section we have contributors from all the repositories under Keploy Organisation, since this is the main project repo, we added that for better recognition. If that can be dynamically rendered - it would be awesome!!

**Comment by nehagup** [comment]
> @nehagup I get it. I'm unaware of any service that provides the ability to dynamically render contributor images for the complete organization - however, I can try to work on a custom workflow/fix for this. I'll keep this PR open and push the changes when done.

That would be awesome! 👏

**Comment by burntcarrot** [comment]
@nehagup I've ran into a major design problem:

- We can fetch the list of contributors through the Github API
   - First, we'll need to fetch the list of repos for the organization through [`api.github.com/orgs/keploy/repos`](https://api.github.com/orgs/keploy/repos)
   - Once we have a list of repos, we can fetch the list of contributors for each repo
   - We'll then eventually need to remove duplicate entries
   - Once everything is done, the `github-actions` bot would update the README (**this is where I feel it becomes too bad - the project commit history should be preserved as it is**)

There are two options:
- Use [contrib.rocks](https://contrib.rocks) for each repo
- Maintain the list of contributors on the website
   - The update process could be automated using the above approach, or could be handled manually.
   - Link the page of contributors under the "Contributors" section in `README`.
   
@slayerjain What do you think?

**Comment by nehagup** [comment]
@burntcarrot thanks for the comment! 

With Approach 1: We can run the workflow during each release or regular intervals (7 days) and having a commit to add new contributors to the readme should be ok. 

With Approach 2: It's not scalable as we'll have to either manually map the list or with [contrib.rocks](https://contrib.rocks/) find unique values.

@slayerjain WDYT?

**Comment by slayerjain** [comment]
@burntcarrot Can you please explain the contrib.rocks approach? AFAIR It doesn't support multi repos. I'm also not a fan of having an automated commit to add new contributors. 

I think using GitHub action and APIs to periodically update a database and then expose that database as a service sounds viable.

**Comment by nehagup** [comment]
@burntcarrot are you still working on this? This PR will be stale in 10 days without any activity and will be closed. :)

**Comment by burntcarrot** [comment]
@nehagup Hi Neha! I've been busy for a couple of weeks in exams - please feel free to close this for now, I'll open up a PR once I'm active.

**Comment by nehagup** [comment]
No worries @burntcarrot! all the best for your exams, closing this for now.

**Pull request closed without merging**
