### PR TITLE
bug: added check for path for added security

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
## Related Issue
  - Info about Issue or bug

Closes: #1143 

#### Describe the changes you've made
I've added a check for the validity of the path and also checked if the path is absolute or not.
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aarishshahmohsin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aarishshahmohsin** [comment]
recheck

**Comment by aarishshahmohsin** [comment]
If there are any changes or information needed for the PR to be merged, please let me know. I'm eager to see this contribution integrated.

**Comment by shivamsouravjha** [comment]
hey @aarishshahmohsin incase you make the PR ask for request (probably with someone who created the issue and assigned you ) this helps in ensuring that folks are aware about your PR

**Comment by aarishshahmohsin** [comment]
> hey @aarishshahmohsin incase you make the PR ask for request (probably with someone who created the issue and assigned you ) this helps in ensuring that folks are aware about your PR

Sorry, if this has caused some inconvenience. If there is a problem with the PR, please mention them.

**Comment by shivamsouravjha** [comment]
Het @aarishshahmohsin would be great if you could explain what you've done/ refactored in this PR? a little explanation would help review the PR

**Comment by aarishshahmohsin** [comment]
I have checked the validity of the path and if the path is absolute or not.

**Comment by aarishshahmohsin** [comment]
@shivamsouravjha is there any update?

**Comment by charankamarapu** [comment]
We already have a validate path function try to use it https://github.com/keploy/keploy/blob/47d3de23877a91334e0bb14de5f41215d9382c50/pkg/proxy/util/util.go#L54

**Comment by aarishshahmohsin** [comment]
> We already have a validate path function try to use it
> 
> https://github.com/keploy/keploy/blob/47d3de23877a91334e0bb14de5f41215d9382c50/pkg/proxy/util/util.go#L54

thanks

**Pull request closed without merging**
